import { BookName } from './BookName';

export const bookNames: BookName[] = [
  {
    fullName: 'Doctrine and Covenants',
    startsWith: 'dc-',
    chapterStartsWith: 'dc-',
  },
  {
    fullName: 'Joseph Smith—History',
    startsWith: 'js-h-',
    chapterStartsWith: 'js-h-',
  },
  { fullName: 'Genesis', startsWith: 'gen-', chapterStartsWith: 'gen-' },
  { fullName: 'Exodus', startsWith: 'ex-', chapterStartsWith: 'ex-' },
  { fullName: 'Leviticus', startsWith: 'lev-', chapterStartsWith: 'lev-' },
  { fullName: 'Numbers', startsWith: 'num-', chapterStartsWith: 'num-' },
  { fullName: 'Deuteronomy', startsWith: 'deut-', chapterStartsWith: 'deut-' },
  { fullName: 'Joshua', startsWith: 'josh-', chapterStartsWith: 'josh-' },
  { fullName: 'Judges', startsWith: 'judg-', chapterStartsWith: 'judg-' },
  { fullName: 'Ruth', startsWith: 'ruth-', chapterStartsWith: 'ruth-' },
  { fullName: '1 Samuel', startsWith: '1_sam-', chapterStartsWith: '1_sam-' },
  { fullName: '2 Samuel', startsWith: '2_sam-', chapterStartsWith: '2_sam-' },
  { fullName: '1 Kings', startsWith: '1_kgs-', chapterStartsWith: '1_kgs-' },
  { fullName: '2 Kings', startsWith: '2_kgs-', chapterStartsWith: '2_kgs-' },
  {
    fullName: '1 Chronicles',
    startsWith: '1_chr-',
    chapterStartsWith: '1_chr-',
  },
  {
    fullName: '2 Chronicles',
    startsWith: '2_chr-',
    chapterStartsWith: '2_chr-',
  },
  { fullName: 'Ezra', startsWith: 'ezra-', chapterStartsWith: 'ezra-' },
  { fullName: 'Nehemiah', startsWith: 'neh-', chapterStartsWith: 'neh-' },
  { fullName: 'Esther', startsWith: 'esth-', chapterStartsWith: 'esth-' },
  { fullName: 'Job', startsWith: 'job-', chapterStartsWith: 'job-' },
  { fullName: 'Psalms', startsWith: 'ps-', chapterStartsWith: 'ps-' },
  { fullName: 'Proverbs', startsWith: 'prov-', chapterStartsWith: 'prov-' },
  { fullName: 'Ecclesiastes', startsWith: 'eccl-', chapterStartsWith: 'eccl-' },
  {
    fullName: 'Song of Solomon',
    startsWith: 'song-',
    chapterStartsWith: 'song-',
  },
  { fullName: 'Isaiah', startsWith: 'isa-', chapterStartsWith: 'isa-' },
  { fullName: 'Jeremiah', startsWith: 'jer-', chapterStartsWith: 'jer-' },
  { fullName: 'Lamentations', startsWith: 'lam-', chapterStartsWith: 'lam-' },
  { fullName: 'Ezekiel', startsWith: 'ezek-', chapterStartsWith: 'ezek-' },
  { fullName: 'Daniel', startsWith: 'dan-', chapterStartsWith: 'dan-' },
  { fullName: 'Hosea', startsWith: 'hosea-', chapterStartsWith: 'hosea-' },
  { fullName: 'Joel', startsWith: 'joel-', chapterStartsWith: 'joel-' },
  { fullName: 'Amos', startsWith: 'amos-', chapterStartsWith: 'amos-' },
  { fullName: 'Obadiah', startsWith: 'obad-', chapterStartsWith: 'obad-' },
  { fullName: 'Jonah', startsWith: 'jonah-', chapterStartsWith: 'jonah-' },
  { fullName: 'Micah', startsWith: 'micah-', chapterStartsWith: 'micah-' },
  { fullName: 'Nahum', startsWith: 'nahum-', chapterStartsWith: 'nahum-' },
  { fullName: 'Habakkuk', startsWith: 'hab-', chapterStartsWith: 'hab-' },
  { fullName: 'Zephaniah', startsWith: 'zeph-', chapterStartsWith: 'zeph-' },
  { fullName: 'Haggai', startsWith: 'hag-', chapterStartsWith: 'hag-' },
  { fullName: 'Zechariah', startsWith: 'zech-', chapterStartsWith: 'zech-' },
  { fullName: 'Malachi', startsWith: 'mal-', chapterStartsWith: 'mal-' },
  { fullName: 'Matthew', startsWith: 'matt-', chapterStartsWith: 'matt-' },
  { fullName: 'Mark', startsWith: 'mark-', chapterStartsWith: 'mark-' },
  { fullName: 'Luke', startsWith: 'luke-', chapterStartsWith: 'luke-' },
  { fullName: 'John', startsWith: 'john-', chapterStartsWith: 'john-' },
  { fullName: 'Acts', startsWith: 'acts-', chapterStartsWith: 'acts-' },
  { fullName: 'Romans', startsWith: 'rom-', chapterStartsWith: 'rom-' },
  {
    fullName: '1 Corinthians',
    startsWith: '1_cor-',
    chapterStartsWith: '1_cor-',
  },
  {
    fullName: '2 Corinthians',
    startsWith: '2_cor-',
    chapterStartsWith: '2_cor-',
  },
  { fullName: 'Galatians', startsWith: 'gal-', chapterStartsWith: 'gal-' },
  { fullName: 'Ephesians', startsWith: 'eph-', chapterStartsWith: 'eph-' },
  {
    fullName: 'Philippians',
    startsWith: 'philip-',
    chapterStartsWith: 'philip-',
  },
  { fullName: 'Colossians', startsWith: 'col-', chapterStartsWith: 'col-' },
  {
    fullName: '1 Thessalonians',
    startsWith: '1_thes-',
    chapterStartsWith: '1_thes-',
  },
  {
    fullName: '2 Thessalonians',
    startsWith: '2_thes-',
    chapterStartsWith: '2_thes-',
  },
  { fullName: '1 Timothy', startsWith: '1_tim-', chapterStartsWith: '1_tim-' },
  { fullName: '2 Timothy', startsWith: '2_tim-', chapterStartsWith: '2_tim-' },
  { fullName: 'Titus', startsWith: 'titus-', chapterStartsWith: 'titus-' },
  { fullName: 'Philemon', startsWith: 'philem-', chapterStartsWith: 'philem-' },
  { fullName: 'Hebrews', startsWith: 'heb-', chapterStartsWith: 'heb-' },
  { fullName: 'James', startsWith: 'james-', chapterStartsWith: 'james-' },
  { fullName: '1 Peter', startsWith: '1_pet-', chapterStartsWith: '1_pet-' },
  { fullName: '2 Peter', startsWith: '2_pet-', chapterStartsWith: '2_pet-' },
  { fullName: '1 John', startsWith: '1_jn-', chapterStartsWith: '1_jn-' },
  { fullName: '2 John', startsWith: '2_jn-', chapterStartsWith: '2_jn-' },
  { fullName: '3 John', startsWith: '3_jn-', chapterStartsWith: '3_jn-' },
  { fullName: 'Jude', startsWith: 'jude-', chapterStartsWith: 'jude-' },
  { fullName: 'Revelations', startsWith: 'rev-', chapterStartsWith: 'rev-' },
  { fullName: '1 Nephi', startsWith: '1_ne-', chapterStartsWith: '1_ne-' },
  { fullName: '2 Nephi', startsWith: '2_ne-', chapterStartsWith: '2_ne-' },
  { fullName: 'Jacob', startsWith: 'jacob-', chapterStartsWith: 'jacob-' },
  { fullName: 'Enos', startsWith: 'enos-', chapterStartsWith: 'enos-' },
  { fullName: 'Jarom', startsWith: 'jarom-', chapterStartsWith: 'jarom-' },
  { fullName: 'Omni', startsWith: 'omni-', chapterStartsWith: 'omni-' },
  { fullName: 'Mosiah', startsWith: 'mosiah-', chapterStartsWith: 'mosiah-' },
  { fullName: 'Alma', startsWith: 'alma-', chapterStartsWith: 'alma-' },
  { fullName: 'Helaman', startsWith: 'hel-', chapterStartsWith: 'hel-' },
  { fullName: '3 Nephi', startsWith: '3_ne-', chapterStartsWith: '3_ne-' },
  { fullName: '4 Nephi', startsWith: '4_ne-', chapterStartsWith: '4_ne-' },
  { fullName: 'Mormon', startsWith: 'morm-', chapterStartsWith: 'morm-' },
  { fullName: 'Ether', startsWith: 'ether-', chapterStartsWith: 'ether-' },
  { fullName: 'Moroni', startsWith: 'moro-', chapterStartsWith: 'moro-' },
  {
    fullName: 'The Testimony of Three Witnesses',
    startsWith: 'bofm/three-',
    chapterStartsWith: 'bofm/three-',
  },
  {
    fullName: 'The Testimony of Eight Witnesses',
    startsWith: 'bofm/eight-',
    chapterStartsWith: 'bofm/eight-',
  },
  {
    fullName: 'The Testimony of the Prophet Joseph Smith',
    startsWith: 'bofm/js',
    chapterStartsWith: 'bofm/js',
  },
  {
    fullName: 'title page of the Book of Mormon',
    startsWith: 'bofm/bofm-title',
    chapterStartsWith: 'bofm/bofm-title',
  },
  {
    fullName: 'Official Declaration',
    startsWith: 'od-',
    chapterStartsWith: 'od-',
  },
  { fullName: 'Moses', startsWith: 'moses-', chapterStartsWith: 'moses-' },
  { fullName: 'Abraham', startsWith: 'abr-', chapterStartsWith: 'abr-' },
  { fullName: 'Ephesians', startsWith: 'eph-', chapterStartsWith: 'eph-' },
  {
    fullName: 'Words of Mormon',
    startsWith: 'w_of_m-',
    chapterStartsWith: 'w_of_m-',
  },
  {
    fullName: 'Joseph Smith–Matthew',
    startsWith: 'js_m-',
    chapterStartsWith: 'js_m-',
  },
  {
    fullName: 'Joseph Smith—History',
    startsWith: 'js_h-',
    chapterStartsWith: 'js_h-',
  },
  {
    fullName: 'Articles of Faith',
    startsWith: 'a_of_f-',
    chapterStartsWith: 'a_of_f-',
  },
];
