import { BookName } from './BookName';

export const bookNames: BookName[] = [
  { fullName: 'Doctrine and Covenants', startsWith: 'dc-' },
  { fullName: 'Joseph Smith—History', startsWith: 'js-h-' },
  { fullName: 'Genesis', startsWith: 'gen-' },
  { fullName: 'Exodus', startsWith: 'ex-' },
  { fullName: 'Leviticus', startsWith: 'lev-' },
  { fullName: 'Numbers', startsWith: 'num-' },
  { fullName: 'Deuteronomy', startsWith: 'deut-' },
  { fullName: 'Joshua', startsWith: 'josh-' },
  { fullName: 'Judges', startsWith: 'judg-' },
  { fullName: 'Ruth', startsWith: 'ruth-' },
  { fullName: '1 Samuel', startsWith: '1-sam-' },
  { fullName: '2 Samuel', startsWith: '2-sam-' },
  { fullName: '1 Kings', startsWith: '1-kgs-' },
  { fullName: '2 Kings', startsWith: '2-kgs-' },
  { fullName: '1 Chronicles', startsWith: '1-chr-' },
  { fullName: '2 Chronicles', startsWith: '2-chr-' },
  { fullName: 'Ezra', startsWith: 'ezra-' },
  { fullName: 'Nehemiah', startsWith: 'neh-' },
  { fullName: 'Esther', startsWith: 'esth-' },
  { fullName: 'Job', startsWith: 'job-' },
  { fullName: 'Psalms', startsWith: 'ps-' },
  { fullName: 'Proverbs', startsWith: 'prov-' },
  { fullName: 'Ecclesiastes', startsWith: 'eccl-' },
  { fullName: 'Song of Solomon', startsWith: 'song-' },
  { fullName: 'Isaiah', startsWith: 'isa-' },
  { fullName: 'Jeremiah', startsWith: 'jer-' },
  { fullName: 'Lamentations', startsWith: 'lam-' },
  { fullName: 'Ezekiel', startsWith: 'ezek-' },
  { fullName: 'Daniel', startsWith: 'dan-' },
  { fullName: 'Hosea', startsWith: 'hosea-' },
  { fullName: 'Joel', startsWith: 'joel-' },
  { fullName: 'Amos', startsWith: 'amos-' },
  { fullName: 'Obadiah', startsWith: 'obad-' },
  { fullName: 'Jonah', startsWith: 'jonah-' },
  { fullName: 'Micah', startsWith: 'micah-' },
  { fullName: 'Nahum', startsWith: 'nahum-' },
  { fullName: 'Habakkuk', startsWith: 'hab-' },
  { fullName: 'Zephaniah', startsWith: 'zeph-' },
  { fullName: 'Haggai', startsWith: 'hag-' },
  { fullName: 'Zechariah', startsWith: 'zech-' },
  { fullName: 'Malachi', startsWith: 'mal-' },
  { fullName: 'Matthew', startsWith: 'matt-' },
  { fullName: 'Mark', startsWith: 'mark-' },
  { fullName: 'Luke', startsWith: 'luke-' },
  { fullName: 'John', startsWith: 'john-' },
  { fullName: 'Acts', startsWith: 'acts-' },
  { fullName: 'Romans', startsWith: 'rom-' },
  { fullName: '1 Corinthians', startsWith: '1-cor-' },
  { fullName: '2 Corinthians', startsWith: '2-cor-' },
  { fullName: 'Galatians', startsWith: 'gal-' },
  { fullName: 'Ephesians', startsWith: 'eph-' },
  { fullName: 'Philippians', startsWith: 'philip-' },
  { fullName: 'Colossians', startsWith: 'col-' },
  { fullName: '1 Thessalonians', startsWith: '1-thes-' },
  { fullName: '2 Thessalonians', startsWith: '2-thes-' },
  { fullName: '1 Timothy', startsWith: '1-tim-' },
  { fullName: '2 Timothy', startsWith: '2-tim-' },
  { fullName: 'Titus', startsWith: 'titus-' },
  { fullName: 'Philemon', startsWith: 'philem-' },
  { fullName: 'Hebrews', startsWith: 'heb-' },
  { fullName: 'James', startsWith: 'james-' },
  { fullName: '1 Peter', startsWith: '1-pet-' },
  { fullName: '2 Peter', startsWith: '2-pet-' },
  { fullName: '1 John', startsWith: '1-jn-' },
  { fullName: '2 John', startsWith: '2-jn-' },
  { fullName: '3 John', startsWith: '3-jn-' },
  { fullName: 'Jude', startsWith: 'jude-' },
  { fullName: 'Revelations', startsWith: 'rev-' },
  { fullName: '1 Nephi', startsWith: '1-ne-' },
  { fullName: '2 Nephi', startsWith: '2-ne-' },
  { fullName: 'Jacob', startsWith: 'jacob-' },
  { fullName: 'Enos', startsWith: 'enos-' },
  { fullName: 'Jarom', startsWith: 'jarom-' },
  { fullName: 'Omni', startsWith: 'omni-' },
  { fullName: 'Mosiah', startsWith: 'mosiah-' },
  { fullName: 'Alma', startsWith: 'alma-' },
  { fullName: 'Helaman', startsWith: 'hel-' },
  { fullName: '3 Nephi', startsWith: '3-ne-' },
  { fullName: '4 Nephi', startsWith: '4-ne-' },
  { fullName: 'Mormon', startsWith: 'morm-' },
  { fullName: 'Ether', startsWith: 'ether-' },
  { fullName: 'Moroni', startsWith: 'moro-' },
  { fullName: 'The Testimony of Three Witnesses', startsWith: 'bofm/three-' },
  { fullName: 'The Testimony of Eight Witnesses', startsWith: 'bofm/eight-' },
  {
    fullName: 'The Testimony of the Prophet Joseph Smith',
    startsWith: 'bofm/js',
  },
  {
    fullName: 'title page of the Book of Mormon',
    startsWith: 'bofm/bofm-title',
  },
  { fullName: 'Official Declaration', startsWith: 'od-' },
  { fullName: 'Moses', startsWith: 'moses-' },
  { fullName: 'Abraham', startsWith: 'abr-' },
  { fullName: 'Ephesians', startsWith: 'eph-' },
  { fullName: 'Words of Mormon', startsWith: 'w-of-m-' },
  { fullName: 'Joseph Smith–Matthew', startsWith: 'js-m-' },
  { fullName: 'Joseph Smith—History', startsWith: 'js-h-' },
  { fullName: 'Articles of Faith', startsWith: 'a-of-f-' },
];
